@WatchTracker.Api_HostAddress = https://localhost:7165

### Register new user
POST {{WatchTracker.Api_HostAddress}}/api/auth/register/
Content-Type: application/json
{
    "email": "example@gmail.com",
    "password": "Example_password_1"
}

### Login user
POST {{WatchTracker.Api_HostAddress}}/api/auth/login/
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "Example_password_1"
}

### Get all watched movies for currently logged user
GET {{WatchTracker.Api_HostAddress}}/api/watched/all/
Authorization: Bearer PASTE_HERE_FROM_LOGIN

### Add new watched movie for currently logged user
POST {{WatchTracker.Api_HostAddress}}/api/watched/add/
Authorization: Bearer PASTE_HERE_FROM_LOGIN
Content-Type: application/json
{
    "title": "Metropolis",
    "description": "Ok, for 100 years old movie.",
    "datewatched": "2026-03-21",
    "rating": 8.5
}